nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'Dokumentacja Twojego API'
            version: '1.0.0'
    areas:
        # Wszystkie kontrolery
        default: ~
